# Mock data for the plant catalogue. In a real application, this would come from a database.
PLANT_CATALOGUE = [
    {
        "id": 1,
        "name": "Tomato",
        "scientific_name": "Solanum lycopersicum",
        "description": "A widely cultivated plant for its edible fruits.",
        "sun_needs": "Full Sun",
        "water_needs": "Moderate",
        "companion_plants": [2, 5],
        "antagonist_plants": [3, 4],
    },
    {
        "id": 2,
        "name": "Basil",
        "scientific_name": "Ocimum basilicum",
        "description": "A culinary herb of the family Lamiaceae.",
        "sun_needs": "Full Sun",
        "water_needs": "Moderate",
        "companion_plants": [1],
        "antagonist_plants": [],
    },
    {
        "id": 3,
        "name": "Cabbage",
        "scientific_name": "Brassica oleracea",
        "description": "A leafy green, red, or white biennial plant grown as an annual vegetable crop.",
        "sun_needs": "Full Sun",
        "water_needs": "High",
        "companion_plants": [],
        "antagonist_plants": [1],
    },
    {
        "id": 4,
        "name": "Fennel",
        "scientific_name": "Foeniculum vulgare",
        "description": "A hardy, perennial herb with yellow flowers and feathery leaves.",
        "sun_needs": "Full Sun",
        "water_needs": "Low",
        "companion_plants": [],
        "antagonist_plants": [1, 6],
    },
    {
        "id": 5,
        "name": "Carrot",
        "scientific_name": "Daucus carota",
        "description": "A root vegetable, usually orange in color, though purple, black, red, white, and yellow cultivars exist.",
        "sun_needs": "Full Sun",
        "water_needs": "Moderate",
        "companion_plants": [1, 6],
        "antagonist_plants": [4],
    },
    {
        "id": 6,
        "name": "Rosemary",
        "scientific_name": "Salvia rosmarinus",
        "description": "A woody, perennial herb with fragrant, evergreen, needle-like leaves and white, pink, purple, or blue flowers.",
        "sun_needs": "Full Sun",
        "water_needs": "Low",
        "companion_plants": [5],
        "antagonist_plants": [],
    },
    {
        "id": 7,
        "name": "Mint",
        "scientific_name": "Mentha",
        "description": "A genus of plants in the family Lamiaceae. The species are not clearly distinct and estimates of the number of species vary.",
        "sun_needs": "Partial Shade",
        "water_needs": "High",
        "companion_plants": [3],
        "antagonist_plants": [],
    }
]
