version: '3.9'

services:
  db_test:
    image: postgres:16-alpine
    container_name: agrotique_db_test
    env_file:
      - .env.test
    ports:
      - "5433:5432"
    networks:
      - agrotique_test_net

  redis_test:
    image: redis:7-alpine
    container_name: agrotique_redis_test
    ports:
      - "6380:6379"
    networks:
      - agrotique_test_net

networks:
  agrotique_test_net:
    driver: bridge
