"""Add plant_catalog table

Revision ID: a1b2c3d4e5f6
Revises: d1b2b3a4a5a6
Create Date: 2024-07-30 12:01:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'd1b2b3a4a5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('plant_type', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sun', sa.String(), nullable=True),
    sa.Column('water', sa.String(), nullable=True),
    sa.Column('spacing', sa.String(), nullable=True),
    sa.Column('planting_season', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('harvest_season', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('compatibility', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_catalog_id'), 'plant_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_plant_catalog_name'), 'plant_catalog', ['name'], unique=False)
    op.create_index(op.f('ix_plant_catalog_plant_type'), 'plant_catalog', ['plant_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_catalog_plant_type'), table_name='plant_catalog')
    op.drop_index(op.f('ix_plant_catalog_name'), table_name='plant_catalog')
    op.drop_index(op.f('ix_plant_catalog_id'), table_name='plant_catalog')
    op.drop_table('plant_catalog')
    # ### end Alembic commands ###
